parameters: {}
environment: {}
packages:
    - name: cronjobs
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: minimap
          binary: false
          main: ""
          runtime: go:default
          web: true
          webSecure: "${OBB_FUNCTION_SECRET}"
          parameters: {}
          environment:
            PG_CONNECTION_STRING: "${PG_CONNECTION_STRING}"
          annotations: {}
          limits: {}
          triggers:
            - name: trigger-minimap
              sourceType: scheduled
              sourceDetails: 
                cron: "*/10 * * * *"
