parameters: {}
environment: {}
packages:
    - name: cronjobs
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: minimap
          binary: false
          main: ""
          runtime: go:default
          web: true
          webSecure: "${OOB_FUNCTION_SECRET}"
          parameters: {}
          environment:
            PG_CONNECTION_STRING: "${PG_CONNECTION_STRING}"
            OBB_FUNCTION_SECRET: "${OBB_FUNCTION_SECRET}"
          annotations: {}
          limits: {}
          # triggers:
          #   - name: trigger-minimap
          #     sourceType: schedule
          #     sourceDetails: 
          #       - cron: "*/10 * * * *"
